### ISSUE TITLE
Add cluster2017 to msf_sum files

### ISSUE THREAD

**Issue by rpitingolo** [NeighborhoodInfoDC/Schools#4]
@ptatian I'm having a really hard time identifying the program that creates the msf_sum files. It looks like it's \Schools\Prog\Master school file\schools_14_15.sas but if you could take a look and confirm that would be helpful. Thanks.

**Comment by lhendey** [comment]
That’s what it looks like to me – towards the bottom.

**Comment by rpitingolo** [comment]
@lhendey Thanks. Hopefully I can update/run this without any trouble. This whole repo could use some cleaning up if we start doing school data again.

**Comment by ptatian** [comment]
The metadata says the "creator process" is **schools_14_15**, so that sounds right.

**Comment by rpitingolo** [comment]
@ptatian thanks!

**Comment by ptatian** [comment]
But, agree that this repo could use a lot of clean up.

**Comment by rpitingolo** [comment]
@lhendey I do already have an issue open for this if you don't mind taking a look.

**Comment by lhendey** [comment]
Cluster2017 is the var name? what format name?

**Comment by rpitingolo** [comment]
$CLUS17A
